### ISSUE TITLE
yarn build gives Cannot find module 'util/' under javascript folder

### ISSUE THREAD

**Issue by augchan42** [BasicPrimitives/react-demo#74]
hosermage@LAPTOP-1RPE37PF:~/react-demo/server/src/static/javascript$ yarn build
yarn run v1.22.15
warning ../../../../../package.json: No license field
$ webpack
[webpack-cli] Failed to load '/home/hosermage/react-demo/server/src/static/javascript/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'util/'
Require stack:
- /home/hosermage/react-demo/server/src/static/javascript/webpack.config.js
- /home/hosermage/node_modules/webpack-cli/lib/webpack-cli.js
- /home/hosermage/node_modules/webpack-cli/lib/bootstrap.js
- /home/hosermage/node_modules/webpack-cli/bin/cli.js
- /home/hosermage/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at Object.<anonymous> (/home/hosermage/react-demo/server/src/static/javascript/webpack.config.js:61:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at WebpackCLI.tryRequireThenImport (/home/hosermage/node_modules/webpack-cli/lib/webpack-cli.js:223:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hosermage/react-demo/server/src/static/javascript/webpack.config.js',
    '/home/hosermage/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/hosermage/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/hosermage/node_modules/webpack-cli/bin/cli.js',
    '/home/hosermage/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by augchan42** [comment]
Ok, issue is my environment was missing some dependencies (I'm a webpack noob).  Here's what you need to run first:
npm install webpack webpack-cli --save-dev
npm install babel-loader @babel/core @babel/preset-env --save-dev
npm install clean-webpack-plugin --save-dev
npm install stream-browserify --save
npm install util --save
npm install process --save
npm install pdfkit-nodejs-webpack --save
npm install blob-stream --save
npm install file-saver --save
