### ISSUE TITLE
Running yarn start from client directory gives Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by augchan42** [BasicPrimitives/react-demo#75]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/hosermage/react-demo/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/hosermage/react-demo/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/hosermage/react-demo/client/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/hosermage/react-demo/client/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/hosermage/react-demo/client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/hosermage/react-demo/client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/hosermage/react-demo/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/hosermage/react-demo/client/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Here's my npm list:

hosermage@LAPTOP-1RPE37PF:~/react-demo/client$ npm list
react-demo@0.1.0 /home/hosermage/react-demo/client
├── @fortawesome/fontawesome-svg-core@1.3.0
├── @fortawesome/free-solid-svg-icons@5.15.4
├── @fortawesome/react-fontawesome@0.1.19
├── @material-ui/core@4.12.4
├── @material-ui/icons@4.11.3
├── @material-ui/lab@4.0.0-alpha.61
├── @material-ui/styles@4.11.5
├── @reach/router@1.3.4
├── @testing-library/jest-dom@5.17.0
├── @testing-library/react@11.2.7
├── @testing-library/user-event@12.8.3
├── axios@0.21.4
├── basicprimitives@6.5.1
├── basicprimitivesreact@6.5.1
├── blob-stream@0.1.3
├── clsx@1.2.1
├── codemirror@5.65.15
├── final-form@4.20.10
├── http-proxy-middleware@1.3.1
├── lodash@4.17.21
├── markdown-react-js@1.0.2
├── pdfkit-nodejs-webpack@0.0.2
├── postcss-safe-parser@7.0.0
├── prop-types@15.8.1
├── react-codemirror2@7.3.0
├── react-device-detect@2.2.3
├── react-dnd-html5-backend@11.1.3
├── react-dnd@11.1.3
├── react-dom@16.14.0
├── react-final-form@6.5.9
├── react-helmet@6.1.0
├── react-live@2.4.1
├── react-redux@7.2.9
├── react-scripts@4.0.0
├── react-sortable-hoc@1.11.0
├── react-syntax-highlighter@15.5.0
├── react-youtube@7.14.0
├── react@16.14.0
├── redial@0.5.0
├── redux-logger@3.0.6
├── redux@4.2.1
├── source-map-explorer@2.5.3
└── web-vitals@0.2.4

**Comment by augchan42** [comment]
Ok, stackexchange is your friend:

export NODE_OPTIONS=--openssl-legacy-provider

Then running yarn-start progresses (but now gives a different error)

**Comment by augchan42** [comment]
https://github.com/BasicPrimitives/react-demo/pull/76 will fix this (along with the other issues encountered)
